-- MySQL Script generated by MySQL Workbench
-- Thu Oct 20 12:32:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Veterinaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veterinaria` (
  `idVeterinaria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(35) NOT NULL,
  `localizacao` VARCHAR(35) NOT NULL,
  `gasto_material` FLOAT NOT NULL,
  `lucro_total` FLOAT NOT NULL,
  PRIMARY KEY (`idVeterinaria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(35) NOT NULL,
  `telefone` VARCHAR(10) NOT NULL,
  `morada` VARCHAR(35) NOT NULL,
  `idVeterinaria` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `idVeterinaria`),
  INDEX `fk_Cliente_Veterinaria1_idx` (`idVeterinaria` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Veterinaria1`
    FOREIGN KEY (`idVeterinaria`)
    REFERENCES `mydb`.`Veterinaria` (`idVeterinaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Animal` (
  `idAnimal` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  `Especie` VARCHAR(15) NOT NULL,
  `Sexo` CHAR(1) NOT NULL,
  `raca` VARCHAR(15) NOT NULL,
  `cor_pelo` VARCHAR(15) NOT NULL,
  `peso` FLOAT NOT NULL,
  `dt_nascimento` VARCHAR(10) NOT NULL,
  `idCliente` INT NOT NULL,
  `idVeterinaria` INT NOT NULL,
  PRIMARY KEY (`idAnimal`, `idCliente`, `idVeterinaria`),
  INDEX `fk_Animal_Cliente_idx` (`idCliente` ASC) VISIBLE,
  INDEX `fk_Animal_Veterinaria1_idx` (`idVeterinaria` ASC) VISIBLE,
  CONSTRAINT `fk_Animal_Cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Animal_Veterinaria1`
    FOREIGN KEY (`idVeterinaria`)
    REFERENCES `mydb`.`Veterinaria` (`idVeterinaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vacina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vacina` (
  `idVacina` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(25) NOT NULL,
  `nome` VARCHAR(25) NOT NULL,
  `quantidade(ml)` FLOAT NOT NULL,
  `preco` FLOAT NOT NULL,
  `data_validade` VARCHAR(8) NOT NULL,
  `Veterinaria_idVeterinaria` INT NOT NULL,
  PRIMARY KEY (`idVacina`, `Veterinaria_idVeterinaria`),
  INDEX `fk_Vacina_Veterinaria1_idx` (`Veterinaria_idVeterinaria` ASC) VISIBLE,
  CONSTRAINT `fk_Vacina_Veterinaria1`
    FOREIGN KEY (`Veterinaria_idVeterinaria`)
    REFERENCES `mydb`.`Veterinaria` (`idVeterinaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Exame` (
  `idExame` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(35) NOT NULL,
  `idVeterinaria` INT NOT NULL,
  PRIMARY KEY (`idExame`, `idVeterinaria`),
  INDEX `fk_Exame_Veterinaria1_idx` (`idVeterinaria` ASC) VISIBLE,
  CONSTRAINT `fk_Exame_Veterinaria1`
    FOREIGN KEY (`idVeterinaria`)
    REFERENCES `mydb`.`Veterinaria` (`idVeterinaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cirurgia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cirurgia` (
  `idCirurgia` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `Veterinaria_idVeterinaria` INT NOT NULL,
  PRIMARY KEY (`idCirurgia`, `Veterinaria_idVeterinaria`),
  INDEX `fk_cirurgia_Veterinaria1_idx` (`Veterinaria_idVeterinaria` ASC) VISIBLE,
  CONSTRAINT `fk_cirurgia_Veterinaria1`
    FOREIGN KEY (`Veterinaria_idVeterinaria`)
    REFERENCES `mydb`.`Veterinaria` (`idVeterinaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Historico_Exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Historico_Exame` (
  `idAnimal` INT NOT NULL,
  `idExame` INT NOT NULL,
  `preco` FLOAT NOT NULL,
  `data_realizacao` VARCHAR(10) NOT NULL,
  `resultado` VARCHAR(45) NOT NULL,
  `Observacao` VARCHAR(45) NULL,
  PRIMARY KEY (`idAnimal`, `idExame`),
  INDEX `fk_Historico_Exame_Animal1_idx` (`idAnimal` ASC) VISIBLE,
  INDEX `fk_Historico_Exame_Exame1_idx` (`idExame` ASC) VISIBLE,
  CONSTRAINT `fk_Historico_Exame_Animal1`
    FOREIGN KEY (`idAnimal`)
    REFERENCES `mydb`.`Animal` (`idAnimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Historico_Exame_Exame1`
    FOREIGN KEY (`idExame`)
    REFERENCES `mydb`.`Exame` (`idExame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Historico_Cirurgia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Historico_Cirurgia` (
  `idAnimal` INT NOT NULL,
  `idcirurgia` INT NOT NULL,
  `data_realizacao` VARCHAR(10) NOT NULL,
  `preco` FLOAT NOT NULL,
  `Observacao` VARCHAR(45) NULL,
  PRIMARY KEY (`idAnimal`, `idcirurgia`),
  INDEX `fk_Historico_Cirurgia_Animal1_idx` (`idAnimal` ASC) VISIBLE,
  INDEX `fk_Historico_Cirurgia_cirurgia1_idx` (`idcirurgia` ASC) VISIBLE,
  CONSTRAINT `fk_Historico_Cirurgia_Animal1`
    FOREIGN KEY (`idAnimal`)
    REFERENCES `mydb`.`Animal` (`idAnimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Historico_Cirurgia_cirurgia1`
    FOREIGN KEY (`idcirurgia`)
    REFERENCES `mydb`.`cirurgia` (`idCirurgia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Historico_Vacina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Historico_Vacina` (
  `idAnimal` INT NOT NULL,
  `idVacina` INT NOT NULL,
  `preco` VARCHAR(45) NOT NULL,
  `data_realizacao` VARCHAR(10) NOT NULL,
  `Observacao` FLOAT NULL,
  PRIMARY KEY (`idAnimal`, `idVacina`),
  INDEX `fk_Historico_Vacina_Vacina1_idx` (`idVacina` ASC) VISIBLE,
  CONSTRAINT `fk_Historico_Vacina_Animal1`
    FOREIGN KEY (`idAnimal`)
    REFERENCES `mydb`.`Animal` (`idAnimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Historico_Vacina_Vacina1`
    FOREIGN KEY (`idVacina`)
    REFERENCES `mydb`.`Vacina` (`idVacina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
